import CipherCore
import Foundation
import SwiftData

/// The local database for one account: messages, conversations, contacts, the outbox and the replay
/// record, behind one serial `ModelActor` so every read sees every earlier write. All APIs take and
/// return `Sendable` domain values; `@Model` objects never leave the actor because they are neither
/// `Sendable` nor safe to read outside the context that fetched them.
///
/// Conformance to `ModelActor` is written out rather than generated by `@ModelActor` because the
/// macro's synthesised initialiser cannot populate `configuration`, and callers need to know which
/// account a store belongs to without hopping onto the actor.
public actor PersistenceStore: ModelActor {
    public nonisolated let modelExecutor: any ModelExecutor
    public nonisolated let modelContainer: ModelContainer
    /// Where this store lives and whose it is.
    public nonisolated let configuration: PersistenceConfiguration

    nonisolated let notifier = ChangeNotifier()
    let clock: any Clock

    /// Opens (creating if needed) the store described by `configuration`. Autosave is off: every
    /// mutation saves explicitly and then notifies observers, so an observer never re-queries a
    /// context that still holds unsaved rows.
    public init(configuration: PersistenceConfiguration, clock: any Clock = SystemClock()) throws(PersistenceError) {
        let container = try PersistenceContainerFactory.makeContainer(configuration)
        let context = ModelContext(container)
        context.autosaveEnabled = false
        self.modelExecutor = DefaultSerialModelExecutor(modelContext: context)
        self.modelContainer = container
        self.configuration = configuration
        self.clock = clock
    }

    /// A store that never touches disk, for previews, tests and the DEBUG demo companion.
    public static func inMemory(accountId: UserID? = nil, clock: any Clock = SystemClock()) throws(PersistenceError) -> PersistenceStore {
        let configuration = accountId.map(PersistenceConfiguration.inMemory(accountId:)) ?? .inMemory
        return try PersistenceStore(configuration: configuration, clock: clock)
    }

    /// The per-account on-disk store under Application Support (see `PersistenceConfiguration.onDisk`).
    public static func onDisk(accountId: UserID, clock: any Clock = SystemClock()) throws(PersistenceError) -> PersistenceStore {
        try PersistenceStore(configuration: try .onDisk(accountId: accountId), clock: clock)
    }

    public nonisolated var accountId: UserID? {
        configuration.accountId
    }
}

// MARK: - Context helpers

extension PersistenceStore {
    var now: Date {
        clock.now()
    }

    func fetch<T: PersistentModel>(_ descriptor: FetchDescriptor<T>) throws(PersistenceError) -> [T] {
        do {
            return try modelContext.fetch(descriptor)
        } catch {
            PersistenceLog.store.error("fetch failed: \(PersistenceError.typeName(of: error), privacy: .public)")
            throw .fetchFailed(PersistenceError.typeName(of: error))
        }
    }

    func fetchFirst<T: PersistentModel>(_ predicate: Predicate<T>) throws(PersistenceError) -> T? {
        var descriptor = FetchDescriptor<T>(predicate: predicate)
        descriptor.fetchLimit = 1
        return try fetch(descriptor).first
    }

    /// Saves pending changes and, only if there were any, tells observers what moved. A failed save
    /// rolls the context back so a poisoned change cannot be dragged into every later save.
    func commit(_ changes: [PersistenceChange]) throws(PersistenceError) {
        guard modelContext.hasChanges else { return }
        do {
            try modelContext.save()
        } catch {
            modelContext.rollback()
            PersistenceLog.store.error("save failed: \(PersistenceError.typeName(of: error), privacy: .public)")
            throw .saveFailed(PersistenceError.typeName(of: error))
        }
        notifier.publish(changes)
    }

    func commit(_ change: PersistenceChange) throws(PersistenceError) {
        try commit([change])
    }
}

// MARK: - Row lookups

extension PersistenceStore {
    func messageRow(id: MessageID) throws(PersistenceError) -> StoredMessage? {
        let uuid = id.uuid
        return try fetchFirst(#Predicate<StoredMessage> { $0.id == uuid })
    }

    func messageRows(ids: [MessageID]) throws(PersistenceError) -> [StoredMessage] {
        guard !ids.isEmpty else { return [] }
        let uuids = ids.map(\.uuid)
        return try fetch(FetchDescriptor<StoredMessage>(predicate: #Predicate { uuids.contains($0.id) }))
    }

    func messageRows(conversationId: ConversationID) throws(PersistenceError) -> [StoredMessage] {
        let uuid = conversationId.uuid
        return try fetch(FetchDescriptor<StoredMessage>(predicate: #Predicate { $0.conversationId == uuid }))
    }

    func conversationRow(id: ConversationID) throws(PersistenceError) -> StoredConversation? {
        let uuid = id.uuid
        return try fetchFirst(#Predicate<StoredConversation> { $0.id == uuid })
    }

    func settingsRow(conversationId: ConversationID) throws(PersistenceError) -> StoredConversationSettings? {
        let uuid = conversationId.uuid
        return try fetchFirst(#Predicate<StoredConversationSettings> { $0.conversationId == uuid })
    }

    func contactRow(userId: UserID) throws(PersistenceError) -> StoredContact? {
        let uuid = userId.uuid
        return try fetchFirst(#Predicate<StoredContact> { $0.userId == uuid })
    }

    func outboxRow(messageId: MessageID) throws(PersistenceError) -> StoredOutboxItem? {
        let uuid = messageId.uuid
        return try fetchFirst(#Predicate<StoredOutboxItem> { $0.messageId == uuid })
    }

    func outboxRows(messageIds: [UUID]) throws(PersistenceError) -> [StoredOutboxItem] {
        guard !messageIds.isEmpty else { return [] }
        return try fetch(FetchDescriptor<StoredOutboxItem>(predicate: #Predicate { messageIds.contains($0.messageId) }))
    }
}
